/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/EvaluationView copy.vue')['default']
    EvaluationView: typeof import('./components/EvaluationView.vue')['default']
    PractiveView: typeof import('./components/PractiveView.vue')['default']
    QuestionView: typeof import('./components/QuestionView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
